# Generated by Django 4.1.3 on 2022-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("deadline_date", models.DateField(blank=True, null=True)),
                ("completion", models.BooleanField()),
                ("tags", models.ManyToManyField(related_name="tags", to="list.tag")),
            ],
            options={
                "ordering": ["completion", "creation_date"],
            },
        ),
    ]
